/*! ver:1428403406 Copyright 2015 Baidu Inc. All Rights Reserved. */;(function(){var l=void 0,n=!0,s=null,u=!1,E=window.BAIDU_DUP_require,H=window.BAIDU_DUP_define;
H&&H("union/common/bom1428403406",[],function(){var g={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(g.g=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Wc=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(g.jd=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Sc=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.dd)&&
(g.ed=+RegExp.$1)}catch(f){}g.Eb=/webkit/i.test(navigator.userAgent);g.sc=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);g.Db="CSS1Compat"==document.compatMode;return{h:g,A:function(){var e=n;if(this.h.g&&(7>this.h.g||"BackCompat"===document.compatMode))e=u;return e},Zc:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.scrollWidth:e.document.documentElement.scrollWidth}catch(f){return 0}},Yc:function(e){try{return e=e||window,"BackCompat"===
e.document.compatMode?e.document.body.scrollHeight:e.document.documentElement.scrollHeight}catch(f){return 0}},D:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientWidth:e.document.documentElement.clientWidth}catch(f){return 0}},o:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientHeight:e.document.documentElement.clientHeight}catch(f){return 0}},F:function(e){e=(e||window).document;return window.pageYOffset||e.documentElement.scrollTop||
e.body.scrollTop},$a:function(e){e=(e||window).document;return window.pageXOffset||e.documentElement.scrollLeft||e.body.scrollLeft},Fb:function(e){var f=u;try{e&&"object"===typeof e&&e.document&&"setInterval"in e&&(f=n)}catch(b){f=u}return f},oa:function(e){e=e||window;return e!=window.top&&e!=e.parent||!this.Fb(e)},Da:function(e,f){for(var f=2===arguments.length?f:e.parent,b=0;10>b++&&this.oa(e,f);){var i;try{i=!!e.parent.location.toString()}catch(d){i=u}if(!i)return n;e=e.parent}return 10<=b?n:
u},Dc:function(e,f){var b=new Image,i="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),f=f||window;f[i]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=s;b=f[i]=s};b.src=e},Ya:function(e){if(!e)return document;"string"===typeof e&&(e=document.getElementById(e));return 9===e.nodeType?e:e.ownerDocument||e.document},ab:function(e){"string"===typeof e&&(e=document.getElementById(e));e=this.Ya(e);return e.parentWindow||e.defaultView||s},ad:function(e){e=e||window;return this.oa(e)&&
!this.Da(e,e.top)&&this.Fb(e.top)?e.top:e}}});
H&&H("union/common/logic1428403406",[],function(){return{Uc:function(g){(g=g||"")&&(g=g.replace(/%u[\d|\w]{4}/g,function(f){return encodeURIComponent(unescape(f))}));return g},R:function(g,f){return g.replace(/{(.*?)}/g,function(e,g){return f[g]||""})},vc:function(g){var f="";window.JSON&&window.JSON.parse&&(f=window.JSON.parse(g));return f},Bb:function(g,f){if(g&&f){var e=g.match(RegExp("(^|&|\\?|#)"+f+"=([^&]*)(&|$)",""));if(e)return e[2]}return s},gd:function(g,f){var g=g||"",f=f||"?",e=arguments.callee;
e.hasOwnProperty[f]||(e[f]={});e=e[f];if(e.hasOwnProperty(g))return e[g];var h={},b=g.indexOf(f),i=g.substring(b+1).split("&");if(-1!==b)for(var b=0,d=i.length;b<d;b++){var a=i[b].split("="),c=decodeURIComponent(a[0]),a=decodeURIComponent(a[1]);h.hasOwnProperty(c)?(h[c].constructor!==Array&&(h[c]=[h[c]]),h[c].push(a)):h[c]=a}return e[g]=h}}});
H&&H("union/common/cookie1428403406",[],function(){return{V:function(g,f){var e,h=RegExp("(^| )"+g+"=([^;]*)(;|$)").exec((f||window).document.cookie);h&&(e=h[2]);return e},ga:function(g,f,e){var e=e||{},h=e.aa;"number"==typeof e.aa&&(h=new Date,h.setTime(h.getTime()+e.aa));document.cookie=""+g+"="+f+(e.path?"; path="+e.path:"")+(h?"; expires="+h.toGMTString():"")+(e.domain?"; domain="+e.domain:"")+(e.kd?"; secure":"")},remove:function(g){var f=new Date;f.setTime(f.getTime()-86400);this.ga(g,"",{path:"/",aa:f})}}});
H&&H("union/preview1428403406",["union/common/bom1428403406","union/common/logic1428403406","union/common/cookie1428403406"],function(g,f,e){function h(b){b=decodeURIComponent(b).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return f.vc(b)}function b(b,d){var a;a=d?d.substring(d.indexOf("?")):g.Da(window)?window.location.search.slice(1):window.top.location.search.slice(1);var c=document.referrer,j=0<=b.indexOf("inlay")||"ui"===b?"bd_cpro_prev":"bd_cpro_fprev",k="",q;try{q=document.cookie}catch(o){}-1!==
a.indexOf(j)&&(k=f.Bb(a,j));!k&&q&&-1!==q.indexOf(j)&&(k=e.V(j));!k&&-1!==c.indexOf(j)&&(k=f.Bb(c,j));return k}return{Za:function(e,d){var a=window.location.href,c=parseInt(e.rsi0,10),j=parseInt(e.rsi1,10),k=parseInt(e.at,10),q=u,o=b(d,a);if(o)if(o=h(o),k===l&&(k=1),1!==parseInt(o.type,10)&&2===(k&2))q=parseInt(o.imgWidth,10)===parseInt(c,10)&&parseInt(o.imgHeight,10)===parseInt(j,10);else if(1===parseInt(o.type,10)&&(1===(k&1)||64===(k&64)||32===(k&32)))q=n;return q?(c=0<=d.indexOf("inlay")||"ui"===
d?"bd_cpro_prev":"bd_cpro_fprev",a=b(d,a),j=e.tn,k=h(a),q=s,0<=d.indexOf("inlay")?q={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(k.type,10)?j+".html":2===parseInt(k.type,10)?"image.html":4===parseInt(k.type,10)?"flash.html":"blank_tips.html")+"?",paramString:(""+c+"=#"+a+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:0<=d.indexOf("float")&&(k=parseInt(k.type,10),k="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===k?"float_image.html":4===k?"float_flash.html":
"blank_tips.html")+"?",a="tn="+j+("&"+c+"="+a).replace(/\./g,"%252e")+"&ut="+ +new Date,q={serviceUrl:k,paramString:a}),q):s}}});
H&&H("union/common/oo1428403406",[],function(){function g(b){var e=g.create(g);return b.call(e,e,e.sb)}function f(b,e){if(b.constructor===Array)for(var d=0,a=b.length;d<a;d++){if(e.call(b,b[d],d,b)===u)return u}else{var d=!{toString:1}.propertyIsEnumerable("toString"),c="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(a in b)if(b.hasOwnProperty(a)&&e.call(b,b[a],a,b)===u)return u;if(d){d=0;for(a=c.length;d<a;d++){var f=c[d];if(b.hasOwnProperty(f)&&
e.call(b,f,d,b)===u)return u}}}return n}function e(b,e,d){f(e,function(a,c){if(!b.hasOwnProperty(c)||d)b[c]=a})}function h(b){function e(){}if(Object.create)return Object.create(b);e.prototype=b;return new e}g.sb={};g.create=h;g.ac=f;g.Ma=function(b){var f,d=b.hasOwnProperty("constructor")?b.constructor:function(){};d.prototype=b;d.prototype.constructor=d;f=f||{};f.kb&&e(d,f.kb);return d};g.extend=function(b,f,d){var a;a=f.hasOwnProperty("constructor")?f.constructor:function(){b.constructor.apply(this,
arguments)};a.prototype=h(b.prototype);e(a.prototype,f,n);a.prototype.constructor=a;a.prototype.Pc=b.prototype;e(a,b);d=d||{};d.kb&&e(a,d.kb,n);return a};g.fd=function(b){var e=this.sb;f(b.split("."),function(b){e.hasOwnProperty(b)||(e[b]={});e=e[b]});return e};g.i=function(b,e){var d;return function(){d=d||[];for(var a=0,c=arguments.length;a<c;a++)d.push(arguments[a]);return b.apply(e||{},d)}};return g});
H&&H("union/common/dom1428403406",["union/common/oo1428403406","union/common/bom1428403406"],function(g,f){return g(function(e){var g=f.h;return{m:function(b,e){return"string"===typeof b||b instanceof String?(e||window).document.getElementById(b):b},Cb:function(b,i){var d=n;if("string"===typeof i)return b.id===i;if(i.constructor===Object)return e.ac(i,function(a,c){var e=(b.getAttribute?b.getAttribute(c):b[c])||b[c];if("tagName"===c){if(e.toUpperCase()!=a.toUpperCase())return d=u}else if(e!=a)return d=u}),d;if(i.constructor===
Array){var a=i.concat([]);a.reverse();for(var c=b;c&&a.length;c=c.parentNode)this.Cb(c,a[0])&&a.shift();return!a.length?n:u}},Nb:function(b,e){if(b&&e(b)!==u){var d=b.childNodes;if(d)for(var a=0,c=d.length;a<c;a++)if(this.Nb(d[a],e)===u)return u}},Kb:function(b,e){var d=this;b.constructor===Object&&(b=this.r(b));if("string"===typeof e){for(var a=document.getElementById(e),c=a;c;){if(c===b)return a;c=c.parentNode}return s}if(e.constructor===Object){var f=s;d.Nb(b,function(a){if(d.Cb(a,e))return f=
a,u});return f}},r:function(b){if(b){if(b.nodeName)return b;1<arguments.length&&(b=Array.prototype.slice.call(arguments,0));if("string"===typeof b)return document.getElementById(b);if(b.constructor===Object)return this.Kb(document.documentElement,b);if(b.constructor===Array){for(var e=b.concat([]),d=document.documentElement;e.length&&d;)d=this.Kb(d,e.shift());return d}}},Bc:function(b,i,d){var d=d||this.od||window,a=d.document;this.wb=0;this.da=this.da||[];this.da.push({Xa:b,vb:i||0,Ta:u});var c=
e.i(function(){var c=u;this.wb++;var b=u;try{d.frameElement&&(b=n)}catch(e){b=n}if(g.g&&9>g.g&&!b)try{a.documentElement.doScroll("left"),c=n}catch(i){}else if("complete"===a.readyState||this.$b)c=n;else if(3E5<this.wb){this.U&&(d.clearInterval(this.U),this.U=s);return}if(c)try{if(this.da&&this.da.length)for(var c=0,f=this.da.length;c<f;c++){var v=this.da[c];v&&v.Xa&&!v.Ta&&(v.vb?(v.Ta=n,d.setTimeout(v.Xa,v.vb)):(v.Ta=n,v.Xa()))}}catch(w){throw w;}finally{this.U&&(d.clearInterval(this.U),this.U=s)}},
this),b=e.i(function(){this.$b=n;c()},this);this.U||(this.U=d.setInterval(c,50),a.addEventListener?(a.addEventListener("DOMContentLoaded",b,u),d.addEventListener("load",b,u)):a.attachEvent&&d.attachEvent("onload",b,u))},A:function(){var b=n;if(g.g&&(7>g.g||"BackCompat"===document.compatMode))b=u;return b},bind:function(b,e,d){"string"===typeof b&&(b=this.r(b));e=e.replace(/^on/i,"").toLowerCase();b.addEventListener?b.addEventListener(e,d,u):b.attachEvent&&b.attachEvent("on"+e,d);return b},Ob:function(b,
e,d){b=this.r(b);if(!b)return s;e=e.replace(/^on/i,"").toLowerCase();b.removeEventListener?b.removeEventListener(e,d,u):b.detachEvent&&b.detachEvent("on"+e,d);return b},t:function(b,e){var d;"string"===typeof b&&(b=this.r(b));var a=f.Ya(b),c="",c=-1<e.indexOf("-")?e.replace(/[-_][^-_]{1}/g,function(a){return a.charAt(1).toUpperCase()}):e.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()});a&&a.defaultView&&a.defaultView.getComputedStyle?((a=a.defaultView.getComputedStyle(b,s))&&
(d=a.getPropertyValue(e)),"boolean"!==typeof d&&!d&&(d=a.getPropertyValue(c))):b.currentStyle&&((a=b.currentStyle)&&(d=a[e]),"boolean"!==typeof d&&!d&&(d=a[c]));return d},nc:function(b,e){e=e||window;"string"===typeof b&&(b=this.r(b));if(b){for(var d=this.ca(b),a,c=0;e!=e.parent&&10>c;)c++,a=this.ca(e.frameElement),d.left+=a.left,d.top+=a.top,e=e.parent;return d}},ca:function(b){"string"===typeof b&&(b=this.r(b));var e=f.Ya(b),d=f.h;0<d.sc&&e.getBoxObjectFor&&this.t(b,"position");var a={left:0,top:0},
c;if(b==(d.g&&!d.Db?e.body:e.documentElement)||!b)return a;if(b.getBoundingClientRect)b=b.getBoundingClientRect(),a.left=Math.floor(b.left)+Math.max(e.documentElement.scrollLeft,e.body.scrollLeft),a.top=Math.floor(b.top)+Math.max(e.documentElement.scrollTop,e.body.scrollTop),a.left-=e.documentElement.clientLeft,a.top-=e.documentElement.clientTop,b=e.body,e=parseInt(this.t(b,"borderLeftWidth"),10),b=parseInt(this.t(b,"borderTopWidth"),10),d.g&&!d.Db&&(a.left-=isNaN(e)?2:e,a.top-=isNaN(b)?2:b);else{c=
b;do{a.left+=c.offsetLeft;a.top+=c.offsetTop;if(0<d.Eb&&"fixed"==this.t(c,"position")){a.left+=e.body.scrollLeft;a.top+=e.body.scrollTop;break}c=c.offsetParent}while(c&&c!=b);if(0<d.opera||0<d.Eb&&"absolute"==this.t(b,"position"))a.top-=e.body.offsetTop;for(c=b.offsetParent;c&&c!=e.body;){a.left-=c.scrollLeft;if(!d.opera||"TR"!=c.tagName)a.top-=c.scrollTop;c=c.offsetParent}}return a},Ab:function(b,e){var b=this.r(b),d=b.offsetWidth;if(e||u)var a=this.t(b,"marginLeft").toString().toLowerCase().replace("px",
"").replace("auto","0"),c=this.t(b,"marginRight").toString().toLowerCase().replace("px","").replace("auto","0"),d=d+(parseInt(a||0,10)+parseInt(c||0,10));return d},zb:function(b,e){var b=this.r(b),d=b.offsetHeight;if(e||u)var a=this.t(b,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),c=this.t(b,"marginBottom").toString().toLowerCase().replace("px","").replace("auto","0"),d=d+(parseInt(a||0,10)+parseInt(c||0,10));return d},$c:function(b){var b=this.r(b),e=this.ab(b),d=0;
if(this.oa(window)&&!f.Da(window)){for(;e.parent!=window.top&&10>d;)d++,e=e.parent;10>d&&(b=e.frameElement||b)}return b},yb:function(b){var e=this.r(b),b=this.ab(e),d=100,a;try{for(;e&&e.tagName;){a=100;if(this.h.g){if(5<this.h.g)try{a=e.Vc.alpha.opacity||100}catch(c){}d=d>a?a:d}else{try{a=100*(b.getComputedStyle(e,s).opacity||1)}catch(f){}d*=a/100}e=e.parentNode}}catch(g){}return d||100},Xc:function(b){for(var e=this.r(b),b=this.ab(e),e=this.yb(e),d=100,a=0;this.oa(b);){a++;if(f.Da(b,b.parent))break;
else d=100,b.frameElement&&(d=this.yb(b.frameElement)),e*=d/100;b=b.parent}return e}}})});
H&&H("union/business/businessLogic1428403406",["union/preview1428403406","union/common/dom1428403406","api"],function(g,f,e){var h={inlay:8,"float":2,patch:2,linkunit:20,popup:1},b={inlay:{},"float":{},patch:{},linkunit:{},popup:{}},i={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};return{qa:function(b){var a=
b._html||{},c="",f="http://cb.baidu.com/ecom?",h=b.id.split("_")[0],i=parseInt(a.conW||0,10)||parseInt(b._w,10)||parseInt(b.sw,10)||parseInt(a.rsi0,10),o=parseInt(a.conH||0,10)||parseInt(b._h,10)||parseInt(b.sh,10)||parseInt(a.rsi1,10),C=b.displayType,v=a.tn||"",w=v.toLowerCase(),B=a.ch||0,m=b.qn||"",r=a.n||"",t=a.dai||0;a.dtm="BAIDU_DUP2_SETJSONADSLOT";a.dc="2";a.di=h;(c=e.getInfo("timestampWathcer"+b.id))&&(a.tt=c.t1+"."+(c.t2-c.t1)+"."+(c.t3-c.t1)+"."+(+new Date-c.t1));var c=[],p;for(p in a)p&&
a.hasOwnProperty(p)&&c.push(""+p+"="+encodeURIComponent(a[p].toString()));c=c.join("&");if((p=g.Za(a,C))&&p.serviceUrl!==l&&p.paramString!==l)f=p.serviceUrl,c=p.paramString;return{slotId:h,slotWidth:i,slotHeight:o,displayType:C,styleType:w,iframeId:"cproIframe_"+h+"_"+a.dai,unionAccount:r,adIndex:t,channel:B,pvId:m,stuffType:"unknown",serviceUrl:f,paramString:c,delayIn:a.delayIn,delayOut:a.delayOut,sessionSync:a.sessionSync!==u&&"false"!==a.sessionSync,closeFor:a.closeFor,xuantingType:a.xuanting,
tn:v}},hb:function(b){var a={};a.Zb=(b.Zb||"pc").toLowerCase();a.B=(b.B||"inlay-fixed").toLowerCase();a.s=(b.s||"template_inlay_all_normal").toLowerCase();a.N=(b.N||"text").toLowerCase();a.K=b.K;if(-1<a.s.indexOf("tlink")||-1<a.s.indexOf("linkunit"))a.B="linkunit-fixed";0<=a.s.indexOf("float_xuanfuwin")&&(a.B="popup-float");b=a.B.split("-");a.Sa=b[0]||"inlay";a.Tc=b[1]||"fixed";return a},Aa:function(b){var b=this.hb(b),a=b.Sa;return this.fc(b)<h[a]},fc:function(d){var d=this.hb(d),a=0,d=b[d.Sa],c;
for(c in d)c&&d[c]&&d.hasOwnProperty(c)&&(f.m(c)?a++:d[c]=l);return a},sa:function(d){d=this.hb(d);b[d.Sa][d.K]=1;return n},Ba:function(b,a){var c=document.getElementById("cpro_"+b);c||(c=document.getElementById(a));return c},hc:function(b){return i[b]},Ha:function(b){var a=b.slotId;E(["viewWatch"],function(c){c.register({id:a,wrapperId:b.iframeId,logType:"block",extra:"ch="+b.channel+"&jk="+b.pvId+"&n="+b.unionAccount})},n)}}});H&&H("union/inlayFixed",["union/business/businessLogic1428403406"],function(g){function f(e){return'<iframe id="{iframeId}" width="{slotWidth}" height="{slotHeight}" src="{serviceUrl}{paramString}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true"></iframe>'.replace(/{(.*?)}/g,function(f,b){return e[b]||""})}return{render:function(e,h){e.displayType="inlay-fixed";var b=g.qa(e),i=g.Ba(b.slotId,h),d={B:b.displayType,s:b.styleType,N:b.stuffType,K:b.iframeId};
if(!g.Aa(d))return u;i.innerHTML=f(b);g.sa(d);g.Ha(b,h)}}});
})();
